### ISSUE TITLE
Combining locale with scopes

### ISSUE THREAD

**Issue by timrwilliams** [mobilityhouse/emobility-i18n#5]
Hi team, interesting gem so thanks for sharing.

Can you comment on your best practice for including different locales within a scope?

e.g. Lets say we are setting global scope based on subdomain as in your example and we have customer1.myapp.com and customer2.myapp.com 

    title: "Awesome Site"
    customer1.title: "Customer1 Site"
    customer1.header "Our own header"
    customer2.title: "Customer 2 Site"

So when somebody visits customer1.myapp.com we set global_scope to "customer1" and them t('title') which works fine.

If you wanted to add multi-language support to a customer where would the locale go and what would you set the global scope to be?

    customer1.en.title
    en.customer1.title

**Comment by aserafin** [comment]
Hi Tim, 

In case multi-language application (let's say English and German) you would have 2 locale files `en.yml` and `de.yml`. In both you should have the same keys just the translations will be different:

en.yml
```
title: "Awesome Site"
customer1.title: "Customer1 Site"
customer1.header "Our own header"
customer2.title: "Customer 2 Site"
```

de.yml

```
title: "ehrfürchtig Website"
customer1.title: "Customer1 Website"
customer1.header "Unsere eigene Kopf"
customer2.title: "Customer2 Website"
```

Just remember that you need to set `I18n.locale` in `before_filter` in your `application_controller.rb` to a correct value (en or de in this case)

**Comment by timrwilliams** [comment]
Makes sense. I just wanted to check that global_scope works alongside locale rather than overriding it. Keep up the good work.
